// Mocks generated by Mockito 5.0.16 from annotations
// in food_recipe/test/src/feature/category_list/data/repositories/category_list_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:food_recipe/src/core/network/network_info.dart' as _i6;
import 'package:food_recipe/src/feature/category_list/data/datasource/category_list_local_datasource.dart'
    as _i5;
import 'package:food_recipe/src/feature/category_list/data/datasource/category_list_remote_datasource.dart'
    as _i3;
import 'package:food_recipe/src/feature/category_list/data/models/category_list_models.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeCategoryListModels_0 extends _i1.Fake
    implements _i2.CategoryListModels {}

/// A class which mocks [CategoryListRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryListRemoteDatasource extends _i1.Mock
    implements _i3.CategoryListRemoteDatasource {
  MockCategoryListRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.CategoryListModels> getCategoryList() => (super.noSuchMethod(
          Invocation.method(#getCategoryList, []),
          returnValue:
              Future<_i2.CategoryListModels>.value(_FakeCategoryListModels_0()))
      as _i4.Future<_i2.CategoryListModels>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [CategoryListLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryListLocalDatasource extends _i1.Mock
    implements _i5.CategoryListLocalDatasource {
  MockCategoryListLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.CategoryListModels> getCategoryList() => (super.noSuchMethod(
          Invocation.method(#getCategoryList, []),
          returnValue:
              Future<_i2.CategoryListModels>.value(_FakeCategoryListModels_0()))
      as _i4.Future<_i2.CategoryListModels>);
  @override
  _i4.Future<void> saveCategoryList(
          _i2.CategoryListModels? categoryListModels) =>
      (super.noSuchMethod(
          Invocation.method(#saveCategoryList, [categoryListModels]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i6.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [CategoryListRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteDataSource extends _i1.Mock
    implements _i3.CategoryListRemoteDatasource {
  MockRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.CategoryListModels> getCategoryList() => (super.noSuchMethod(
          Invocation.method(#getCategoryList, []),
          returnValue:
              Future<_i2.CategoryListModels>.value(_FakeCategoryListModels_0()))
      as _i4.Future<_i2.CategoryListModels>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [CategoryListLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalDataSource extends _i1.Mock
    implements _i5.CategoryListLocalDatasource {
  MockLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.CategoryListModels> getCategoryList() => (super.noSuchMethod(
          Invocation.method(#getCategoryList, []),
          returnValue:
              Future<_i2.CategoryListModels>.value(_FakeCategoryListModels_0()))
      as _i4.Future<_i2.CategoryListModels>);
  @override
  _i4.Future<void> saveCategoryList(
          _i2.CategoryListModels? categoryListModels) =>
      (super.noSuchMethod(
          Invocation.method(#saveCategoryList, [categoryListModels]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  String toString() => super.toString();
}
