// Mocks generated by Mockito 5.0.16 from annotations
// in food_recipe/test/src/feature/category_list/data/datasource/category_list_local_datasource_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:drift/src/runtime/executor/stream_queries.dart' as _i4;
import 'package:food_recipe/src/feature/category_list/data/models/category_list_models.dart'
    as _i6;
import 'package:food_recipe/src/feature/category_list/data/table/category_list_table.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:moor_flutter/moor_flutter.dart' as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeCategoryListDatabase_0 extends _i1.Fake
    implements _i2.CategoryListDatabase {}

class _FakeDatabaseConnection_1 extends _i1.Fake
    implements _i3.DatabaseConnection {}

class _FakeSqlTypeSystem_2 extends _i1.Fake implements _i3.SqlTypeSystem {}

class _FakeQueryExecutor_3 extends _i1.Fake implements _i3.QueryExecutor {}

class _FakeStreamQueryStore_4 extends _i1.Fake implements _i4.StreamQueryStore {
}

class _FakeDatabaseConnectionUser_5 extends _i1.Fake
    implements _i3.DatabaseConnectionUser {}

class _FakeInsertStatement_6<T extends _i3.Table, D> extends _i1.Fake
    implements _i3.InsertStatement<T, D> {}

class _FakeUpdateStatement_7<T extends _i3.Table, D> extends _i1.Fake
    implements _i3.UpdateStatement<T, D> {}

class _FakeSimpleSelectStatement_8<T extends _i3.HasResultSet, D>
    extends _i1.Fake implements _i3.SimpleSelectStatement<T, D> {}

class _FakeJoinedSelectStatement_9<FirstT extends _i3.HasResultSet, FirstD>
    extends _i1.Fake implements _i3.JoinedSelectStatement<FirstT, FirstD> {}

class _FakeDeleteStatement_10<T extends _i3.Table, D> extends _i1.Fake
    implements _i3.DeleteStatement<T, D> {}

class _FakeSelectable_11<T> extends _i1.Fake implements _i3.Selectable<T> {}

class _FakeGenerationContext_12 extends _i1.Fake
    implements _i3.GenerationContext {}

/// A class which mocks [CategoryListDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryListDatabase extends _i1.Mock
    implements _i2.CategoryListDatabase {
  MockCategoryListDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get schemaVersion =>
      (super.noSuchMethod(Invocation.getter(#schemaVersion), returnValue: 0)
          as int);
  @override
  String toString() => super.toString();
}

/// A class which mocks [CategoryListDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryListDao extends _i1.Mock implements _i2.CategoryListDao {
  MockCategoryListDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CategoryListDatabase get db => (super.noSuchMethod(Invocation.getter(#db),
      returnValue: _FakeCategoryListDatabase_0()) as _i2.CategoryListDatabase);
  @override
  set db(_i2.CategoryListDatabase? _db) =>
      super.noSuchMethod(Invocation.setter(#db, _db),
          returnValueForMissingStub: null);
  @override
  _i2.CategoryListDatabase get attachedDatabase => (super.noSuchMethod(
      Invocation.getter(#attachedDatabase),
      returnValue: _FakeCategoryListDatabase_0()) as _i2.CategoryListDatabase);
  @override
  _i3.DatabaseConnection get connection =>
      (super.noSuchMethod(Invocation.getter(#connection),
          returnValue: _FakeDatabaseConnection_1()) as _i3.DatabaseConnection);
  @override
  _i3.SqlTypeSystem get typeSystem =>
      (super.noSuchMethod(Invocation.getter(#typeSystem),
          returnValue: _FakeSqlTypeSystem_2()) as _i3.SqlTypeSystem);
  @override
  _i3.QueryExecutor get executor =>
      (super.noSuchMethod(Invocation.getter(#executor),
          returnValue: _FakeQueryExecutor_3()) as _i3.QueryExecutor);
  @override
  _i4.StreamQueryStore get streamQueries =>
      (super.noSuchMethod(Invocation.getter(#streamQueries),
          returnValue: _FakeStreamQueryStore_4()) as _i4.StreamQueryStore);
  @override
  _i3.DatabaseConnectionUser get resolvedEngine =>
      (super.noSuchMethod(Invocation.getter(#resolvedEngine),
              returnValue: _FakeDatabaseConnectionUser_5())
          as _i3.DatabaseConnectionUser);
  @override
  _i5.Future<dynamic> getCategoryList() =>
      (super.noSuchMethod(Invocation.method(#getCategoryList, []),
          returnValue: Future<dynamic>.value()) as _i5.Future<dynamic>);
  @override
  _i5.Future<List<_i6.CategoryModels>> getCategories() => (super.noSuchMethod(
          Invocation.method(#getCategories, []),
          returnValue:
              Future<List<_i6.CategoryModels>>.value(<_i6.CategoryModels>[]))
      as _i5.Future<List<_i6.CategoryModels>>);
  @override
  _i5.Future<void> saveCategoryList(_i3.Insertable<dynamic>? categoryList) =>
      (super.noSuchMethod(Invocation.method(#saveCategoryList, [categoryList]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i5.Future<void>);
  @override
  _i5.Stream<List<Map<String, Object?>>> createStream(
          _i4.QueryStreamFetcher? stmt) =>
      (super.noSuchMethod(Invocation.method(#createStream, [stmt]),
              returnValue: Stream<List<Map<String, Object?>>>.empty())
          as _i5.Stream<List<Map<String, Object?>>>);
  @override
  T alias<T extends _i3.Table, D>(_i3.TableInfo<T, D>? table, String? alias) =>
      (super.noSuchMethod(Invocation.method(#alias, [table, alias]),
          returnValue: null) as T);
  @override
  void markTablesUpdated(Iterable<_i3.TableInfo<_i3.Table, dynamic>>? tables) =>
      super.noSuchMethod(Invocation.method(#markTablesUpdated, [tables]),
          returnValueForMissingStub: null);
  @override
  void notifyUpdates(Set<_i3.TableUpdate>? updates) =>
      super.noSuchMethod(Invocation.method(#notifyUpdates, [updates]),
          returnValueForMissingStub: null);
  @override
  _i5.Stream<Set<_i3.TableUpdate>> tableUpdates(
          [_i3.TableUpdateQuery? query = const _i3.TableUpdateQuery.any()]) =>
      (super.noSuchMethod(Invocation.method(#tableUpdates, [query]),
              returnValue: Stream<Set<_i3.TableUpdate>>.empty())
          as _i5.Stream<Set<_i3.TableUpdate>>);
  @override
  _i5.Future<T> doWhenOpened<T>(
          _i5.FutureOr<T>? Function(_i3.QueryExecutor)? fn) =>
      (super.noSuchMethod(Invocation.method(#doWhenOpened, [fn]),
          returnValue: Future<T>.value(null)) as _i5.Future<T>);
  @override
  _i3.InsertStatement<T, D> into<T extends _i3.Table, D>(
          _i3.TableInfo<T, D>? table) =>
      (super.noSuchMethod(Invocation.method(#into, [table]),
              returnValue: _FakeInsertStatement_6<T, D>())
          as _i3.InsertStatement<T, D>);
  @override
  _i3.UpdateStatement<Tbl, R> update<Tbl extends _i3.Table, R>(
          _i3.TableInfo<Tbl, R>? table) =>
      (super.noSuchMethod(Invocation.method(#update, [table]),
              returnValue: _FakeUpdateStatement_7<Tbl, R>())
          as _i3.UpdateStatement<Tbl, R>);
  @override
  _i3.SimpleSelectStatement<T, R> select<T extends _i3.HasResultSet, R>(
          _i3.ResultSetImplementation<T, R>? table,
          {bool? distinct = false}) =>
      (super.noSuchMethod(
              Invocation.method(#select, [table], {#distinct: distinct}),
              returnValue: _FakeSimpleSelectStatement_8<T, R>())
          as _i3.SimpleSelectStatement<T, R>);
  @override
  _i3.JoinedSelectStatement<T, R> selectOnly<T extends _i3.HasResultSet, R>(
          _i3.ResultSetImplementation<T, R>? table,
          {bool? distinct = false}) =>
      (super.noSuchMethod(
              Invocation.method(#selectOnly, [table], {#distinct: distinct}),
              returnValue: _FakeJoinedSelectStatement_9<T, R>())
          as _i3.JoinedSelectStatement<T, R>);
  @override
  _i3.DeleteStatement<T, D> delete<T extends _i3.Table, D>(
          _i3.TableInfo<T, D>? table) =>
      (super.noSuchMethod(Invocation.method(#delete, [table]),
              returnValue: _FakeDeleteStatement_10<T, D>())
          as _i3.DeleteStatement<T, D>);
  @override
  _i5.Future<int> customUpdate(String? query,
          {List<_i3.Variable<dynamic>>? variables = const [],
          Set<_i3.TableInfo<_i3.Table, dynamic>>? updates,
          _i3.UpdateKind? updateKind}) =>
      (super.noSuchMethod(
          Invocation.method(#customUpdate, [
            query
          ], {
            #variables: variables,
            #updates: updates,
            #updateKind: updateKind
          }),
          returnValue: Future<int>.value(0)) as _i5.Future<int>);
  @override
  _i5.Future<int> customInsert(String? query,
          {List<_i3.Variable<dynamic>>? variables = const [],
          Set<_i3.TableInfo<_i3.Table, dynamic>>? updates}) =>
      (super.noSuchMethod(
          Invocation.method(#customInsert, [query],
              {#variables: variables, #updates: updates}),
          returnValue: Future<int>.value(0)) as _i5.Future<int>);
  @override
  _i5.Future<List<_i3.QueryRow>> customWriteReturning(String? query,
          {List<_i3.Variable<dynamic>>? variables = const [],
          Set<_i3.TableInfo<_i3.Table, dynamic>>? updates,
          _i3.UpdateKind? updateKind}) =>
      (super.noSuchMethod(
              Invocation.method(#customWriteReturning, [
                query
              ], {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind
              }),
              returnValue: Future<List<_i3.QueryRow>>.value(<_i3.QueryRow>[]))
          as _i5.Future<List<_i3.QueryRow>>);
  @override
  _i3.Selectable<_i3.QueryRow> customSelect(String? query,
          {List<_i3.Variable<dynamic>>? variables = const [],
          Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom =
              const {}}) =>
      (super.noSuchMethod(
              Invocation.method(#customSelect, [query],
                  {#variables: variables, #readsFrom: readsFrom}),
              returnValue: _FakeSelectable_11<_i3.QueryRow>())
          as _i3.Selectable<_i3.QueryRow>);
  @override
  _i3.Selectable<_i3.QueryRow> customSelectQuery(String? query,
          {List<_i3.Variable<dynamic>>? variables = const [],
          Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom =
              const {}}) =>
      (super.noSuchMethod(
              Invocation.method(#customSelectQuery, [query],
                  {#variables: variables, #readsFrom: readsFrom}),
              returnValue: _FakeSelectable_11<_i3.QueryRow>())
          as _i3.Selectable<_i3.QueryRow>);
  @override
  _i5.Future<void> customStatement(String? statement, [List<dynamic>? args]) =>
      (super.noSuchMethod(
          Invocation.method(#customStatement, [statement, args]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i5.Future<void>);
  @override
  _i5.Future<T> transaction<T>(_i5.Future<T> Function()? action) =>
      (super.noSuchMethod(Invocation.method(#transaction, [action]),
          returnValue: Future<T>.value(null)) as _i5.Future<T>);
  @override
  _i5.Future<void> batch(_i5.FutureOr<void>? Function(_i3.Batch)? runInBatch) =>
      (super.noSuchMethod(Invocation.method(#batch, [runInBatch]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i5.Future<void>);
  @override
  _i3.GenerationContext $write(_i3.Component? component,
          {bool? hasMultipleTables}) =>
      (super.noSuchMethod(
          Invocation.method(
              #$write, [component], {#hasMultipleTables: hasMultipleTables}),
          returnValue: _FakeGenerationContext_12()) as _i3.GenerationContext);
  @override
  _i3.GenerationContext $writeInsertable(
          _i3.TableInfo<_i3.Table, dynamic>? table,
          _i3.Insertable<dynamic>? insertable) =>
      (super.noSuchMethod(
          Invocation.method(#$writeInsertable, [table, insertable]),
          returnValue: _FakeGenerationContext_12()) as _i3.GenerationContext);
  @override
  String toString() => super.toString();
}
