// Mocks generated by Mockito 5.0.16 from annotations
// in food_recipe/test/src/feature/category_list/presentation/bloc/category_list_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:food_recipe/src/core/error/failure.dart' as _i6;
import 'package:food_recipe/src/core/usecase/usecase.dart' as _i8;
import 'package:food_recipe/src/feature/category_list/domain/entities/category_list.dart'
    as _i7;
import 'package:food_recipe/src/feature/category_list/domain/repositories/category_list_repository.dart'
    as _i2;
import 'package:food_recipe/src/feature/category_list/domain/usecases/get_category_list.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeCategoryListRepository_0 extends _i1.Fake
    implements _i2.CategoryListRepository {}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

/// A class which mocks [GetCategoryList].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCategoryList extends _i1.Mock implements _i4.GetCategoryList {
  MockGetCategoryList() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CategoryListRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
              returnValue: _FakeCategoryListRepository_0())
          as _i2.CategoryListRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.CategoryList>> call(
          _i8.NoParams? noParams) =>
      (super.noSuchMethod(Invocation.method(#call, [noParams]),
          returnValue: Future<_i3.Either<_i6.Failure, _i7.CategoryList>>.value(
              _FakeEither_1<_i6.Failure, _i7.CategoryList>())) as _i5
          .Future<_i3.Either<_i6.Failure, _i7.CategoryList>>);
  @override
  String toString() => super.toString();
}
